config/routes.rb
Rails.application.routes.draw do
  resources :stories

  root 'tasks#index'

  resources :tasks

  resources :statuscodes

end

app/models/concerns/common.rb
################################################################################################
#
#  ＜Commonモジュールの使い方＞
#   ・ modelクラスに、「include Common」を追加してください。
#   ・ 画面で更新する際に、根元になるクラスに「after_commit :dump」を追加してください。
#      ※ 親子関係やコード値テーブルなど、根元になるクラスに紐づいているテーブルの情報は
#        再帰処理で表示するため、根元のクラスだけ記載すればよいです。
#
#  ＜Commonモジュールの動作＞
#   ・ 根元のクラスのテーブルに対するコミットが完了した後に、dumpメソッドが実行されます。
#   ・ 現在は、テーブルに保存した結果がLV1ディレクトリの直下に「YYYYMMDD_HHMMSS.txt」という名前で
#      出力されます。
#
#　　＜注意点＞
#　　　・コード値関係のクラス名はお約束として、末尾を「code」で終わるようにしてください。
#        例：Statuscodeクラス（テーブル名はstatuscodes）
#
#   CTI高綱魔改造
#　　・ファイル出力する直前でキーと値のペアをハッシュに入れる
#    ・ハッシュをJSONにする
#    ・標準出力に吐き出す（STDOUT.puts）
#
################################################################################################
module Common
  def dump
    f = File.open("./LV1/#{Time.now.strftime("%Y%m%d_%H%M%S")}.txt", 'w')
    @@h = {}

    dump_recursive (f)

    f.close
    STDOUT.puts "●●●ここから●●●"
    STDOUT.puts(@@h.to_json)
    STDOUT.puts "●●●ここまで●●●"
    
  end

  LIST_OF_EXCLUSION = ["id", "created_at", "updated_at"]
  #dumpの再帰処理を行う。
  def dump_recursive (f)


    self.attributes.each{ |key, val|
      # 表示用の項目名に翻訳しつつ、その時の項目名を表示する。
      unless LIST_OF_EXCLUSION.include?(key)  # 除外リストに含まれる項目名は表示しない
      key_view = I18n.translate("activerecord.attributes."+self.class.name.downcase+"."+key)

      if key.include? "code_id"
        #末尾に「code_id」がある項目はクラスから名称を取得する。（現状name固定）
        f.puts "#{key_view} #{key.sub(/_id$/,"").classify.constantize.find(val).name}"
        @@h.store(key_view,key.sub(/_id$/,"").classify.constantize.find(val).name)
      elsif  key.include? "_id"
        ##再帰処理
        data = key.sub(/_id$/,"").classify.constantize.find(val)
        data.dump_recursive(f) if data.present?
      else
        f.puts "#{key_view} #{val}"
        @@h.store(key_view,val)
      end

    end
    }
  end


end

app/models/statuscode.rb
class Statuscode < ActiveRecord::Base
  include Common
  
end

app/models/story.rb
class Story < ActiveRecord::Base
  include Common
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  include Common
  belongs_to :statuscode
  belongs_to :story
  after_commit :dump

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statuscodes_controller.rb
class StatuscodesController < ApplicationController
  before_action :set_statuscode, only: [:show, :edit, :update, :destroy]

  # GET /statuscodes
  # GET /statuscodes.json
  def index
    @statuscodes = Statuscode.all
  end

  # GET /statuscodes/1
  # GET /statuscodes/1.json
  def show
  end

  # GET /statuscodes/new
  def new
    @statuscode = Statuscode.new
  end

  # GET /statuscodes/1/edit
  def edit
  end

  # POST /statuscodes
  # POST /statuscodes.json
  def create
    @statuscode = Statuscode.new(statuscode_params)

    respond_to do |format|
      if @statuscode.save
        format.html { redirect_to @statuscode, notice: 'Statuscodes was successfully created.' }
        format.json { render :show, statuscodes: :created, location: @statuscode }
      else
        format.html { render :new }
        format.json { render json: @statuscode.errors, statuscodes: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuscodes/1
  # PATCH/PUT /statuscodes/1.json
  def update
    respond_to do |format|
      if @statuscode.update(statuscode_params)
        format.html { redirect_to @statuscode, notice: 'Statuscodes was successfully updated.' }
        format.json { render :show, statuscodes: :ok, location: @statuscode }
      else
        format.html { render :edit }
        format.json { render json: @statuscode.errors, statuscodes: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuscodes/1
  # DELETE /statuscodes/1.json
  def destroy
    @statuscode.destroy
    respond_to do |format|
      format.html { redirect_to statuscodes_url, notice: 'Statuscodes was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statuscode
      @statuscode = Statuscode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statuscode_params
      params.require(:statuscode).permit(:name)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :limit, :statuscode_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuscodes_helper.rb
module StatuscodesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/statuscodes/_form.html.erb
<%= form_for(@statuscode) do |f| %>
  <% if @statuscode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statuscode.errors.count, "error") %> prohibited this statuscode from being saved:</h2>

      <ul>
      <% @statuscode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuscodes/edit.html.erb
<h1>Editing statuscode</h1>

<%= render 'form' %>

<%= link_to 'Show', @statuscode %> |
<%= link_to 'Back', statuscodes_path %>

app/views/statuscodes/index.html.erb
<h1>Listing statuscodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuscodes.each do |statuscode| %>
      <tr>
        <td><%= statuscode.name %></td>
        <td><%= link_to 'Show', statuscode %></td>
        <td><%= link_to 'Edit', edit_statuscode_path(statuscode) %></td>
        <td><%= link_to 'Destroy', statuscode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_statuscode_path %>

app/views/statuscodes/new.html.erb
<h1>New statuscode</h1>

<%= render 'form' %>

<%= link_to 'Back', statuscodes_path %>

app/views/statuscodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @statuscode.name %>
</p>

<%= link_to 'Edit', edit_statuscode_path(@statuscode) %> |
<%= link_to 'Back', statuscodes_path %>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.datetime_select :limit %>
  </div>


  <div class="field">
    <%= f.label :statuscode_id %><br>
    <%= f.collection_select( :statuscode_id, Statuscode.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.task.title') %></th>
      <th><%= t('activerecord.attributes.task.description') %></th>
      <th><%= t('activerecord.attributes.task.limit') %></th>
      <th><%= t('activerecord.attributes.task.status_id') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.limit %></td>
        <td><%= task.statuscode_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.task.title') %></strong>
  <%= @task.title %>
</p>

<p>
  <strong><%= t('activerecord.attributes.task.description') %></strong>
  <%= @task.description %>
</p>

<p>
  <strong><%= t('activerecord.attributes.task.limit') %></strong>
  <%= @task.limit %>
</p>

<p>
  <strong><%= t('activerecord.attributes.task.status_id') %></strong>
  <%= @task.statuscode.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>